[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "https://veggie-rezepte.de/*"
  to = "https://www.veggie-rezepte.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"